version: '3.8'

services:
  discord-bot:
    build: .
    container_name: discord-copilot-bot
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - PYTHONPATH=/app
    volumes:
      - ./logs:/app/logs
    networks:
      - bot-network
    depends_on:
      - redis
    healthcheck:
      test: ["CMD", "python", "-c", "import discord; print('Bot OK')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  redis:
    image: redis:7-alpine
    container_name: discord-bot-redis
    restart: unless-stopped
    volumes:
      - redis_data:/data
    networks:
      - bot-network
    command: redis-server --appendonly yes

  # Optional: Database for persistent storage
  postgres:
    image: postgres:15-alpine
    container_name: discord-bot-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: discordbot
      POSTGRES_USER: botuser
      POSTGRES_PASSWORD: ${DB_PASSWORD:-botpassword}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - bot-network

networks:
  bot-network:
    driver: bridge

volumes:
  redis_data:
  postgres_data:
