apiVersion: v2
name: discord-bot
description: A Discord bot with OpenAI ChatGPT integration
type: application
version: 0.1.0
appVersion: "1.0.0"

keywords:
  - discord
  - bot
  - openai
  - chatgpt
  - ai

maintainers:
  - name: Your Name
    email: your.email@example.com

sources:
  - https://github.com/your-org/discord-openai-bot

dependencies:
  - name: redis
    version: "19.6.4"
    repository: "https://charts.bitnami.com/bitnami"
    condition: redis.enabled
